const SKILLS = [
                  { value: 'HTML', label: 'HTML', rating: 0, filter: 'React'},
                  { value: 'CSS', label: 'CSS' , rating: 0, filter: 'React'},
                  { value: 'JavaScript', label: 'JavaScript' , rating: 0, filter: 'React'},
                  { value: 'Rails', label: 'Rails' , rating: 0, filter: 'ROR'},
                  { value: 'ERP', label: 'ERP' , rating: 0, filter: 'ROR'},
                  { value: 'Postgres', label: 'Postgres' , rating: 0, filter: 'ROR'},
                  { value: 'Swift', label: 'Swift' , rating: 0, filter: 'IOS'},
                  { value: 'Objective C', label: 'Objective C' , rating: 0, filter: 'IOS'},
                  { value: 'Express', label: 'Express' , rating: 0, filter: 'NodeJS'},
                  { value: 'Redux', label: 'Redux' , rating: 0, filter: 'React'},
                  { value: 'Flux', label: 'Flux' , rating: 0, filter: 'React'},
                  { label: "React js", value: "React js", rating: 0, filter: 'React'},
                  { label: "React Native Developer", value: "React Native Developer", rating: 0, filter: 'React'},
                  { label: "ReactJS & React Native Engineer", value: "ReactJS & React Native Engineer", rating: 0, filter: 'React'},
                  { label: "React Developer", value: "React Developer", rating: 0, filter: 'React'},
                  { label: "Reactjs issue fix", value: "Reactjs issue fix", rating: 0, filter: 'React'},
                  { label: "React Developer", value: "React Developer", rating: 0, filter: 'React'},
                  { label: "React Native", value: "React Native", rating: 0, filter: 'React'},
                  { label: "Ror Backend Developer", value: "Ror Backend Developer", rating: 0, filter: 'ROR'},
                  { label: "RoR Developer", value: "RoR Developer", rating: 0, filter: 'ROR'},
                  { label: "iOS Product Engineer", value: "iOS Product Engineer", rating: 0, filter: 'IOS'},
                  { label: "iOS Engineer", value: "iOS Engineer", rating: 0, filter: 'IOS'},
                  { label: "iOS Developer", value: "iOS Developer", rating: 0, filter: 'IOS'},
                  { label: "iOS Freelancer", value: "iOS Freelancer", rating: 0, filter: 'IOS'},
                  { label: "iOS Developer", value: "iOS Developer", rating: 0, filter: 'IOS'},
                  { label: "iOS application Developer", value: "iOS application Developer", rating: 0, filter: 'IOS'},
                  { label: "iOS/Android Developer", value: "iOS/Android Developer", rating: 0, filter: 'IOS'},
                  { label: "IOS Developer", value: "IOS Developer", rating: 0, filter: 'IOS'},
                  { label: "node backend", value: "node backend", rating: 0, filter: 'NodeJS'},
                  { label: "Nodejs ,React js,Php", value: "Nodejs ,React js,Php", rating: 0, filter: 'NodeJS'},
                  { label: "Node.js, Golang, React", value: "Node.js, Golang, React", rating: 0, filter: 'NodeJS'},
                  { label: "Node.js ", value: "Node.js", rating: 0, filter: 'NodeJS'},
                  { label: "NodeJs", value: "NodeJs", rating: 0, filter: 'NodeJS'},
                  { label:"Salesforce Consultant", value: "Salesforce Consultant", filter: 'Salesforce'},
                  { label:"Salesforce Lightning Consultant", value: "Salesforce Lightning Consultant", filter: 'Salesforce'},
                  { label:"Salesforce Architect", value: "Salesforce Architect", filter: 'Salesforce'},
                  { label:"Salesforce Developer", value: "Salesforce Developer", filter: 'Salesforce'},
                  { label:"Salesforce Administrator", value: "Salesforce Administrator", filter: 'Salesforce'},
                  { label:"Salesforce Advanced Administrator", value: "Salesforce Advanced Administrator", filter: 'Salesforce'},
                  { label:"Salesforce Data Architecture and Management Designer", value: "Salesforce Data Architecture and Management Designer", filter: 'Salesforce'},
                  { label:"Salesforce Sharing and Visibility Designer", value: "Salesforce Sharing and Visibility Designer", filter: 'Salesforce'},
                  { label:"Salesforce Platform Developer", value: "Salesforce Platform Developer", filter: 'Salesforce'},
                  { label:"Salesforce App Builder", value: "Salesforce App Builder", filter: 'Salesforce'},
                  { label:"Salesforce Technical Architect", value: "Salesforce Technical Architect", filter: 'Salesforce'},
                  { label:"Salesforce Application Architect", value: "Salesforce Application Architect", filter: 'Salesforce'},
                  { label:"Salesforce Systems Architect", value: "Salesforce Systems Architect", filter: 'Salesforce'},
                  { label:"Salesforce Community Cloud Consultant", value: "Salesforce Community Cloud Consultant", filter: 'Salesforce'},
                  { label:"Salesforce Mobile Solutions Architecture Designer", value: "Salesforce Mobile Solutions Architecture Designer", filter: 'Salesforce'},
                  { label:"Salesforce Development Lifecycle and Deployment Designer", value: "Salesforce Development Lifecycle and Deployment Designer", filter: 'Salesforce'},
                  { label:"Salesforce Identity and Access Management Designer", value: "Salesforce Identity and Access Management Designer", filter: 'Salesforce'},
                  { label:"Salesforce Integration Architecture Designer", value: "Salesforce Integration Architecture Designer", filter: 'Salesforce'},
                  { label:"Salesforce Sales Cloud Consultant", value: "Salesforce Sales Cloud Consultant", filter: 'Salesforce'},
                  { label:"Salesforce Service Cloud Consultant", value: "Salesforce Service Cloud Consultant", filter: 'Salesforce'},
                  { label:"Salesforce Marketing Cloud Email Specialist", value: "Salesforce Marketing Cloud Email Specialist", filter: 'Salesforce'},
                  { label:"Salesforce Marketing Cloud Consultant", value: "Salesforce Marketing Cloud Consultant", filter: 'Salesforce'},
                  { label:"Salesforce Mobile Connect Expert", value: "Salesforce Mobile Connect Expert", filter: 'Salesforce'},
                  { label:"Salesforce Pardot", value: "Salesforce Pardot", filter: 'Salesforce'},
                  { label:"Salesforce Data Analyst", value: "Salesforce Data Analyst", filter: 'Salesforce'},
                  { label:"Salesforce Einstein Analytics", value: "Salesforce Einstein Analytics", filter: 'Salesforce'},
                  { label:"Salesforce CPQ Consultant", value: "Salesforce CPQ Consultant", filter: 'Salesforce'},
                  { label:"Salesforce DX Consultant", value: "Salesforce DX Consultant", filter: 'Salesforce'},
                  { label:"Salesforce Business Analyst", value: "Salesforce Business Analyst", filter: 'Salesforce'},
                  { label:"Salesforce Solutions Architect", value: "Salesforce Solutions Architect", filter: 'Salesforce'},
                  { label:"Salesforce Consultant - Functional", value: "Salesforce Consultant - Functional", filter: 'Salesforce'},
                  { label:"Salesforce Consultant - Technical", value: "Salesforce Consultant - Technical", filter: 'Salesforce'},
                  { label:"Salesforce Developer / Programmer", value: "Salesforce Developer / Programmer", filter: 'Salesforce'},
                  { label:"Salesforce Consultant Administrator", value: "Salesforce Consultant Administrator", filter: 'Salesforce'},
                  { label:"Salesforce Technical Architect", value: "Salesforce Technical Architect", filter: 'Salesforce'}
                ]  

export default SKILLS;


