const SKILLS = [
                  { value: 'HTML', label: 'HTML', rating: 0},
                  { value: 'CSS', label: 'CSS' , rating: 0},
                  { value: 'JavaScript', label: 'JavaScript' , rating: 0},
                  { value: 'Rails', label: 'Rails' , rating: 0},
                  { value: 'ERP', label: 'ERP' , rating: 0},
                  { value: 'Postgres', label: 'Postgres' , rating: 0},
                  { value: 'Swift', label: 'Swift' , rating: 0},
                  { value: 'Objective C', label: 'Objective C' , rating: 0},
                  { value: 'Express', label: 'Express' , rating: 0},
                  { value: 'Redux', label: 'Redux' , rating: 0},
                  { value: 'Flux', label: 'Flux' , rating: 0},
                  { label: "React js", value: "React js", rating: 0},
                  { label: "React Native Developer", value: "React Native Developer", rating: 0},
                  { label: "ReactJS & React Native Engineer", value: "ReactJS & React Native Engineer", rating: 0},
                  { label: "React Developer", value: "React Developer", rating: 0},
                  { label: "react", value: "react", rating: 0},
                  { label: "Reactjs issue fix", value: "Reactjs issue fix", rating: 0},
                  { label: "React Developer", value: "React Developer", rating: 0},
                  { label: "React Native", value: "React Native", rating: 0},
                  { label: "RealTime Quality Enforcer", value: "RealTime Quality Enforcer", rating: 0},
                  { label: "Research Scientist Intern", value: "Research Scientist Intern", rating: 0},
                  { label: "Research Scientist", value: "Research Scientist", rating: 0},
                  { label: "Resource Management Analyst", value: "Resource Management Analyst", rating: 0},
                  { label: "Recruitment", value: "Recruitment", rating: 0},
                  { label: "Remote Software Engineer", value: "Remote Software Engineer", rating: 0},
                  { label: "Resident ", value: "Resident ", rating: 0},
                  { label: "Regional advisor", value: "Regional advisor", rating: 0},
                  { label: "Research Associate", value: "Research Associate", rating: 0},
                  { label: "Reservoir Geophysicist", value: "Reservoir Geophysicist", rating: 0},
                  { label: "Research Assitant", value: "Research Assitant", rating: 0},
                  { label: "Research work online", value: "Research work online", rating: 0},
                  { label: "Remote Data Science Intern", value: "Remote Data Science Intern", rating: 0},
                  { label: "Regional HR Director", value: "Regional HR Director", rating: 0},
                  { label: "Research Intern", value: "Research Intern", rating: 0},
                  { label: "Research Analyst", value: "Research Analyst", rating: 0},
                  { label: "Research Assistant", value: "Research Assistant", rating: 0},
                  { label: "Researcher and Project Manager", value: "Researcher and Project Manager", rating: 0},
                  { label: "Regional Manager", value: "Regional Manager", rating: 0},
                  { label: "Researcher", value: "Researcher", rating: 0},
                  { label: "Regional Technology Manager", value: "Regional Technology Manager", rating: 0},
                  { label: "Requirements Engineer", value: "Requirements Engineer", rating: 0},
                  { label: "Recruiter", value: "Recruiter", rating: 0},
                  { label: "Ror Backend Developer", value: "Ror Backend Developer", rating: 0},
                  { label: "RoR Developer", value: "RoR Developer", rating: 0},
                  { label: "Robotic Process Automation Developer", value: "Robotic Process Automation Developer", rating: 0},
                  { label: "ROS", value: "ROS", rating: 0},
                  { label: "iOS Product Engineer", value: "iOS Product Engineer", rating: 0},
                  { label: "iOS Engineer", value: "iOS Engineer", rating: 0},
                  { label: "iOS Developer", value: "iOS Developer", rating: 0},
                  { label: "iOS Freelancer", value: "iOS Freelancer", rating: 0},
                  { label: "iOS Developer", value: "iOS Developer", rating: 0},
                  { label: "iOS application Developer", value: "iOS application Developer", rating: 0},
                  { label: "iOS/Android Developer", value: "iOS/Android Developer", rating: 0},
                  { label: "IOS Developer", value: "IOS Developer", rating: 0},
                  { label: "Sales roles", value: "Sales roles", rating: 0},
                  { label: "sales engineer", value: "sales engineer", rating: 0},
                  { label: "Sales & Business Development", value: "Sales & Business Development", rating: 0},
                  { label: "Sales ", value: "Sales", rating: 0},
                  { label: "SAS Devoloper", value: "SAS Devoloper", rating: 0},
                  { label: "SAP Mobile Architect and Consultant", value: "SAP Mobile Architect and Consultant", rating: 0},
                  { label: "Sap", value: "Sap", rating: 0},
                  { label: "SAP MM/WM ", value: "SAP MM/WM", rating: 0},
                  { label: "node backend", value: "node backend", rating: 0},
                  { label: "Nodejs ,React js,Php", value: "Nodejs ,React js,Php", rating: 0},
                  { label: "Node.js, Golang, React", value: "Node.js, Golang, React", rating: 0},
                  { label: "Node.js ", value: "Node.js", rating: 0},
                  { label: "NodeJs", value: "NodeJs", rating: 0},
                  { label: "NOC / SOC Analyst", value: "NOC / SOC Analyst", rating: 0},
                  { label:"Salesforce Consultant", value: "Salesforce Consultant"},
                  { label:"Salesforce Lightning Consultant", value: "Salesforce Lightning Consultant"},
                  { label:"Salesforce Architect", value: "Salesforce Architect"},
                  { label:"Salesforce Developer", value: "Salesforce Developer"},
                  { label:"Salesforce Administrator", value: "Salesforce Administrator"},
                  { label:"Salesforce Advanced Administrator", value: "Salesforce Advanced Administrator"},
                  { label:"Salesforce Data Architecture and Management Designer", value: "Salesforce Data Architecture and Management Designer"},
                  { label:"Salesforce Sharing and Visibility Designer", value: "Salesforce Sharing and Visibility Designer"},
                  { label:"Salesforce Platform Developer", value: "Salesforce Platform Developer"},
                  { label:"Salesforce App Builder", value: "Salesforce App Builder"},
                  { label:"Salesforce Technical Architect", value: "Salesforce Technical Architect"},
                  { label:"Salesforce Application Architect", value: "Salesforce Application Architect"},
                  { label:"Salesforce Systems Architect", value: "Salesforce Systems Architect"},
                  { label:"Salesforce Community Cloud Consultant", value: "Salesforce Community Cloud Consultant"},
                  { label:"Salesforce Mobile Solutions Architecture Designer", value: "Salesforce Mobile Solutions Architecture Designer"},
                  { label:"Salesforce Development Lifecycle and Deployment Designer", value: "Salesforce Development Lifecycle and Deployment Designer"},
                  { label:"Salesforce Identity and Access Management Designer", value: "Salesforce Identity and Access Management Designer"},
                  { label:"Salesforce Integration Architecture Designer", value: "Salesforce Integration Architecture Designer"},
                  { label:"Salesforce Sales Cloud Consultant", value: "Salesforce Sales Cloud Consultant"},
                  { label:"Salesforce Service Cloud Consultant", value: "Salesforce Service Cloud Consultant"},
                  { label:"Salesforce Marketing Cloud Email Specialist", value: "Salesforce Marketing Cloud Email Specialist"},
                  { label:"Salesforce Marketing Cloud Consultant", value: "Salesforce Marketing Cloud Consultant"},
                  { label:"Salesforce Mobile Connect Expert", value: "Salesforce Mobile Connect Expert"},
                  { label:"Salesforce Pardot", value: "Salesforce Pardot"},
                  { label:"Salesforce Data Analyst", value: "Salesforce Data Analyst"},
                  { label:"Salesforce Einstein Analytics", value: "Salesforce Einstein Analytics"},
                  { label:"Salesforce CPQ Consultant", value: "Salesforce CPQ Consultant"},
                  { label:"Salesforce DX Consultant", value: "Salesforce DX Consultant"},
                  { label:"Salesforce Business Analyst", value: "Salesforce Business Analyst"},
                  { label:"Salesforce Solutions Architect", value: "Salesforce Solutions Architect"},
                  { label:"Salesforce Consultant - Functional", value: "Salesforce Consultant - Functional"},
                  { label:"Salesforce Consultant - Technical", value: "Salesforce Consultant - Technical"},
                  { label:"Salesforce Developer / Programmer", value: "Salesforce Developer / Programmer"},
                  { label:"Salesforce Consultant Administrator", value: "Salesforce Consultant Administrator"},
                  { label:"Salesforce Technical Architect", value: "Salesforce Technical Architect"}
                ]  

export default SKILLS;


