const TIMEZONES = [
	{
	  "code": "KT1072",
	  "name": "Dateline Standard Time",
	  "offset": "-43200",
	  "time": "(GMT-12:00) International Date Line West",
	},
	{
	  "code": "NL8253",
	  "name": "Samoa Standard Time",
	  "offset": "-39600",
	  "time": "(GMT-11:00) Midway Island, Samoa",
	},
	{
	  "code": "KI1674",
	  "name": "Hawaiian Standard Time",
	  "offset": "-36000",
	  "time": "(GMT-10:00) Hawaii",
	},
	{
	  "code": "JX3324",
	  "name": "Alaskan Standard Time",
	  "offset": "-32400",
	  "time": "(GMT-09:00) Alaska",
	},
	{
	  "code": "ZB2216",
	  "name": "Pacific Standard Time",
	  "offset": "-28800",
	  "time": "(GMT-08:00) Pacific Time (US and Canada) Tijuana",
	},
	{
	  "code": "OQ2611",
	  "name": "Mountain Standard Time",
	  "offset": "-25200",
	  "time": "(GMT-07:00) Mountain Time (US and Canada)",
	},
	{
	  "code": "WT9427",
	  "name": "Mexico Standard Time 2",
	  "offset": "-25200",
	  "time": "(GMT-07:00) Chihuahua, La Paz, Mazatlan",
	},
	{
	  "code": "RF8640",
	  "name": "U.S. Mountain Standard Time",
	  "offset": "-25200",
	  "time": "(GMT-07:00) Arizona",
	},
	{
	  "code": "HM7369",
	  "name": "Central Standard Time",
	  "offset": "-21600",
	  "time": "(GMT-06:00) Central Time (US and Canada)",
	},
	{
	  "code": "EO2449",
	  "name": "Canada Central Standard Time",
	  "offset": "-21600",
	  "time": "(GMT-06:00) Saskatchewan",
	},
	{
	  "code": "EE2734",
	  "name": "Mexico Standard Time",
	  "offset": "-21600",
	  "time": "(GMT-06:00) Guadalajara, Mexico City, Monterrey",
	},
	{
	  "code": "IS7078",
	  "name": "Central America Standard Time",
	  "offset": "-21600",
	  "time": "(GMT-06:00) Central America",
	},
	{
	  "code": "CL9121",
	  "name": "Eastern Standard Time",
	  "offset": "-18000",
	  "time": "(GMT-05:00) Eastern Time (US and Canada)",
	},
	{
	  "code": "YZ7713",
	  "name": "U.S. Eastern Standard Time",
	  "offset": "-18000",
	  "time": "(GMT-05:00) Indiana (East)",
	},
	{
	  "code": "GJ2527",
	  "name": "S.A. Pacific Standard Time",
	  "offset": "-18000",
	  "time": "(GMT-05:00) Bogota, Lima, Quito",
	},
	{
	  "code": "OJ2368",
	  "name": "Atlantic Standard Time",
	  "offset": "-14400",
	  "time": "(GMT-04:00) Atlantic Time (Canada)",
	},
	{
	  "code": "UI6845",
	  "name": "S.A. Western Standard Time",
	  "offset": "-14400",
	  "time": "(GMT-04:00) Caracas, La Paz",
	},
	{
	  "code": "NK8478",
	  "name": "Pacific S.A. Standard Time",
	  "offset": "-14400",
	  "time": "(GMT-04:00) Santiago",
	},
	{
	  "code": "YV7252",
	  "name": "Newfoundland and Labrador Standard Time",
	  "offset": "-12600",
	  "time": "(GMT-03:30) Newfoundland and Labrador",
	},
	{
	  "code": "PW4015",
	  "name": "E. South America Standard Time",
	  "offset": "-10800",
	  "time": "(GMT-03:00) Brasilia",
	},
	{
	  "code": "DL3642",
	  "name": "S.A. Eastern Standard Time",
	  "offset": "-10800",
	  "time": "(GMT-03:00) Buenos Aires, Georgetown",
	},
	{
	  "code": "RE1415",
	  "name": "Greenland Standard Time",
	  "offset": "-10800",
	  "time": "(GMT-03:00) Greenland",
	},
	{
	  "code": "DE8179",
	  "name": "Mid-Atlantic Standard Time",
	  "offset": "-7200",
	  "time": "(GMT-02:00) Mid-Atlantic",
	},
	{
	  "code": "VU8317",
	  "name": "Azores Standard Time",
	  "offset": "-3600",
	  "time": "(GMT-01:00) Azores",
	},
	{
	  "code": "XM2522",
	  "name": "Cape Verde Standard Time",
	  "offset": "-3600",
	  "time": "(GMT-01:00) Cape Verde Islands",
	},
	{
	  "code": "PS6859",
	  "name": "GMT Standard Time",
	  "offset": "0",
	  "time": "(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London",
	},
	{
	  "code": "NP9532",
	  "name": "Greenwich Standard Time",
	  "offset": "0",
	  "time": "(GMT) Casablanca, Monrovia",
	},
	{
	  "code": "TT2624",
	  "name": "Central Europe Standard Time",
	  "offset": "3600",
	  "time": "(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
	},
	{
	  "code": "JS8645",
	  "name": "Central European Standard Time",
	  "offset": "3600",
	  "time": "(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
	},
	{
	  "code": "MS5652",
	  "name": "Romance Standard Time",
	  "offset": "3600",
	  "time": "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris",
	},
	{
	  "code": "UD4838",
	  "name": "W. Europe Standard Time",
	  "offset": "3600",
	  "time": "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
	},
	{
	  "code": "ZV4555",
	  "name": "W. Central Africa Standard Time",
	  "offset": "3600",
	  "time": "(GMT+01:00) West Central Africa",
	},
	{
	  "code": "SC5967",
	  "name": "E. Europe Standard Time",
	  "offset": "7200",
	  "time": "(GMT+02:00) Bucharest",
	},
	{
	  "code": "NH6112",
	  "name": "Egypt Standard Time",
	  "offset": "7200",
	  "time": "(GMT+02:00) Cairo",
	},
	{
	  "code": "RK6555",
	  "name": "FLE Standard Time",
	  "offset": "7200",
	  "time": "(GMT+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
	},
	{
	  "code": "QN8279",
	  "name": "GTB Standard Time",
	  "offset": "7200",
	  "time": "(GMT+02:00) Athens, Istanbul, Minsk",
	},
	{
	  "code": "TX7921",
	  "name": "Israel Standard Time",
	  "offset": "7200",
	  "time": "(GMT+02:00) Jerusalem",
	},
	{
	  "code": "GQ7252",
	  "name": "South Africa Standard Time",
	  "offset": "7200",
	  "time": "(GMT+02:00) Harare, Pretoria",
	},
	{
	  "code": "TF7931",
	  "name": "Russian Standard Time",
	  "offset": "10800",
	  "time": "(GMT+03:00) Moscow, St. Petersburg, Volgograd",
	},
	{
	  "code": "IQ1246",
	  "name": "Arab Standard Time",
	  "offset": "10800",
	  "time": "(GMT+03:00) Kuwait, Riyadh",
	},
	{
	  "code": "LK8649",
	  "name": "E. Africa Standard Time",
	  "offset": "10800",
	  "time": "(GMT+03:00) Nairobi",
	},
	{
	  "code": "SV7476",
	  "name": "Arabic Standard Time",
	  "offset": "10800",
	  "time": "(GMT+03:00) Baghdad",
	},
	{
	  "code": "ZQ3413",
	  "name": "Iran Standard Time",
	  "offset": "12600",
	  "time": "(GMT+03:30) Tehran",
	},
	{
	  "code": "XF3739",
	  "name": "Arabian Standard Time",
	  "offset": "14400",
	  "time": "(GMT+04:00) Abu Dhabi, Muscat",
	},
	{
	  "code": "YM3922",
	  "name": "Caucasus Standard Time",
	  "offset": "14400",
	  "time": "(GMT+04:00) Baku, Tbilisi, Yerevan",
	},
	{
	  "code": "WN4374",
	  "name": "Transitional Islamic State of Afghanistan Standard Time",
	  "offset": "16200",
	  "time": "(GMT+04:30) Kabul",
	},
	{
	  "code": "KT2871",
	  "name": "Ekaterinburg Standard Time",
	  "offset": "18000",
	  "time": "(GMT+05:00) Ekaterinburg",
	},
	{
	  "code": "VE2728",
	  "name": "West Asia Standard Time",
	  "offset": "18000",
	  "time": "(GMT+05:00) Islamabad, Karachi, Tashkent",
	},
	{
	  "code": "EX3752",
	  "name": "India Standard Time",
	  "offset": "19800",
	  "time": "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
	},
	{
	  "code": "PC9364",
	  "name": "Nepal Standard Time",
	  "offset": "20700",
	  "time": "(GMT+05:45) Kathmandu",
	},
	{
	  "code": "RI1837",
	  "name": "Central Asia Standard Time",
	  "offset": "21600",
	  "time": "(GMT+06:00) Astana, Dhaka",
	},
	{
	  "code": "MO8651",
	  "name": "Sri Lanka Standard Time",
	  "offset": "21600",
	  "time": "(GMT+06:00) Sri Jayawardenepura",
	},
	{
	  "code": "PB2678",
	  "name": "N. Central Asia Standard Time",
	  "offset": "21600",
	  "time": "(GMT+06:00) Almaty, Novosibirsk",
	},
	{
	  "code": "WI5943",
	  "name": "Myanmar Standard Time",
	  "offset": "23400",
	  "time": "(GMT+06:30) Yangon Rangoon",
	},
	{
	  "code": "GZ5518",
	  "name": "S.E. Asia Standard Time",
	  "offset": "25200",
	  "time": "(GMT+07:00) Bangkok, Hanoi, Jakarta",
	},
	{
	  "code": "AY1464",
	  "name": "North Asia Standard Time",
	  "offset": "25200",
	  "time": "(GMT+07:00) Krasnoyarsk",
	},
	{
	  "code": "JG7673",
	  "name": "China Standard Time",
	  "offset": "28800",
	  "time": "(GMT+08:00) Beijing, Chongqing, Hong Kong SAR, Urumqi",
	},
	{
	  "code": "VE8762",
	  "name": "Singapore Standard Time",
	  "offset": "28800",
	  "time": "(GMT+08:00) Kuala Lumpur, Singapore",
	},
	{
	  "code": "MB8037",
	  "name": "Taipei Standard Time",
	  "offset": "28800",
	  "time": "(GMT+08:00) Taipei",
	},
	{
	  "code": "TE3414",
	  "name": "W. Australia Standard Time",
	  "offset": "28800",
	  "time": "(GMT+08:00) Perth",
	},
	{
	  "code": "MW8051",
	  "name": "North Asia East Standard Time",
	  "offset": "28800",
	  "time": "(GMT+08:00) Irkutsk, Ulaanbaatar",
	},
	{
	  "code": "AR3130",
	  "name": "Korea Standard Time",
	  "offset": "32400",
	  "time": "(GMT+09:00) Seoul",
	},
	{
	  "code": "DQ6462",
	  "name": "Tokyo Standard Time",
	  "offset": "32400",
	  "time": "(GMT+09:00) Osaka, Sapporo, Tokyo",
	},
	{
	  "code": "HR4115",
	  "name": "Yakutsk Standard Time",
	  "offset": "32400",
	  "time": "(GMT+09:00) Yakutsk",
	},
	{
	  "code": "LW8774",
	  "name": "A.U.S. Central Standard Time",
	  "offset": "34200",
	  "time": "(GMT+09:30) Darwin",
	},
	{
	  "code": "YA5516",
	  "name": "Cen. Australia Standard Time",
	  "offset": "34200",
	  "time": "(GMT+09:30) Adelaide",
	},
	{
	  "code": "TG8242",
	  "name": "A.U.S. Eastern Standard Time",
	  "offset": "36000",
	  "time": "(GMT+10:00) Canberra, Melbourne, Sydney",
	},
	{
	  "code": "XS9236",
	  "name": "E. Australia Standard Time",
	  "offset": "36000",
	  "time": "(GMT+10:00) Brisbane",
	},
	{
	  "code": "JR3263",
	  "name": "Tasmania Standard Time",
	  "offset": "36000",
	  "time": "(GMT+10:00) Hobart",
	},
	{
	  "code": "TC5359",
	  "name": "Vladivostok Standard Time",
	  "offset": "36000",
	  "time": "(GMT+10:00) Vladivostok",
	},
	{
	  "code": "KV2764",
	  "name": "West Pacific Standard Time",
	  "offset": "36000",
	  "time": "(GMT+10:00) Guam, Port Moresby",
	},
	{
	  "code": "FD3466",
	  "name": "Central Pacific Standard Time",
	  "offset": "39600",
	  "time": "(GMT+11:00) Magadan, Solomon Islands, New Caledonia",
	},
	{
	  "code": "TM8378",
	  "name": "Fiji Islands Standard Time",
	  "offset": "43200",
	  "time": "(GMT+12:00) Fiji Islands, Kamchatka, Marshall Islands",
	},
	{
	  "code": "QH7073",
	  "name": "New Zealand Standard Time",
	  "offset": "43200",
	  "time": "(GMT+12:00) Auckland, Wellington",
	},
	{
	  "code": "NB2817",
	  "name": "Tonga Standard Time",
	  "offset": "46800",
	  "time": "(GMT+13:00) Nukualofa",
	}
  ] 

export default TIMEZONES;


