export const CAMPAIGN_FETCH_DATA_SUCCESS = "CAMPAIGN_FETCH_DATA_SUCCESS";
export const CAMPAIGN_FETCH_SUCCESS = "CAMPAIGN_FETCH_SUCCESS";
export const CAMPAIGN_DELETE_SUCCESS = "CAMPAIGN_DELETE_SUCCESS";
export const SELECTED_CAMPAIGN_UPDATED = "SELECTED_CAMPAIGN_UPDATED";
export const CAMPAIGN_PLAY_FETCH_DATA_SUCCESS = "CAMPAIGN_PLAY_FETCH_DATA_SUCCESS";
export const SELECTED_CAMPAIGN_PLAY_UPDATED = "SELECTED_CAMPAIGN_PLAY_UPDATED";
export const SELECTED_CAMPAIGN_PLAY_EMAIL = "SELECTED_CAMPAIGN_PLAY_EMAIL";
export const CONNECT_CAMPAIGN_PLAY_EMAIL = "CONNECT_CAMPAIGN_PLAY_EMAIL";
export const CONNECTED_FETCH_DATA_SUCCESS = "CONNECTED_FETCH_DATA_SUCCESS";
export const SCRAPING_FETCH_DATA_SUCCESS = "SCRAPING_FETCH_DATA_SUCCESS";
export const MEMBER_FETCH_DATA_SUCCESS = "MEMBER_FETCH_DATA_SUCCESS";


export const DASHBOARD_FETCH_DATA_SUCCESS = "DASHBOARD_FETCH_DATA_SUCCESS";


export const LOGS_FETCH_SUCCESS = "LOGS_FETCH_SUCCESS";